### ISSUE TITLE
Better logs from tasks

### ISSUE THREAD

**Issue by kodipe** [dromejs/drome#1]
Definitely Drome need great logs from running tasks. In my opinion it has to log:

- start and finish of task
- time spent on specific task
- log from task

It would be nice if everything will be colorized.

**Comment by mikeerickson** [comment]
@kodipe Do you want the logs to be in console only, or also written to file.  Further, if written to file, do you want the log stored in the project root (thinking a log per project would be better than a global log file).

```
<projectRoot>/drome.log
```

As far as content, I am thinking try to keep it as consistent with other logging services (such as npm)

**Comment by mikeerickson** [comment]
log format...

```
[timestamp] <task> start
[timestamp] <task> end
```

Other metrics could be calculated if running tasks series 

Note: `seriesId` could be a simple value (processId or something), just something to group and identify

````
[timestamp] <seriesId> start
[timestamp] <task> start
[timestamp] <task> end
[timestamp] <task> start
[timestamp] <task> end
[timestamp] <seriesId> end
[timestamp] <seriesId> total
```

**Comment by kodipe** [comment]
@mikeerickson I have planned logging to file, which could be enabled through additional configuration. I think that log should be created per project. Global log file is always annoying if user have to analyse logs.

When it comes to logs format, timestamp would be helpful (will be very similar to Gulp logs ;) ). I'm not sure what do you mean by seriesId. For now every task is described by "object path" e.g. `firstLevel.subtask.sequence` which is unique and allow user easily find specific task in configuration.

**Comment by kodipe** [comment]
@mikeerickson please look at #19. Let's discuss there about additional configuration.
