### ISSUE TITLE
Add CLI option to suppress the `start` and `finish` output

### ISSUE THREAD

**Issue by mikeerickson** [dromejs/drome#11]
## Feature Request

If you have some suggestion in mind please describe:

- **Feature** you need and **use case** - description of problem
- **Documentation** - how users will be able to use the new feature

I know it seems meaningless, but how about an option to suppress the internal `Started task ...` and `Finished task ...`

```bash
drome <task> --silent or -S
```

If you are keep for PRs let me know and I will assist where I have reported other issues

**Comment by kodipe** [comment]
Thanks for this issue!
It would be really nice feature. I wonder if we need also option for silence tasks output or only Drome logs?

**Comment by mikeerickson** [comment]
@kodipe I think this would be a good start, and users can control themselves.  If you need a PR for this (or anything else) I would be happy to help.

**Comment by kodipe** [comment]
@mikeerickson yes, please create PR. Thanks a lot for all your contribution! 

There are initial lines of code for retrieving arguments from  CLI: https://github.com/dromejs/drome/blob/e176e67b0433d761264278150d03ea200534f8e4/lib/cli.js#L1
so you can improve that.

**Comment by mikeerickson** [comment]
@kodipe sounds good, I would be happy to help.  Just an FYI, we are moving over the weekend into a new house, I will try and knock this one out tomorrow before the move, otherwise it might not be until Sunday or Monday
