### ISSUE TITLE
When executing npm scripts, it should honor ansi output

### ISSUE THREAD

**Issue by mikeerickson** [dromejs/drome#12]
## Feature Request

If I execute the following from terminal, all is good (as you can see, there is color output)

![image](https://user-images.githubusercontent.com/183153/45520356-da80ea00-b76d-11e8-8bda-86e1e8f7d331.png)

However, if I execute the same script from within `drome` it does not output the color

![image](https://user-images.githubusercontent.com/183153/45520379-f71d2200-b76d-11e8-8a14-7a0ac27ccb2d.png)

**Comment by kodipe** [comment]
When I'm trying to run within `drome` e.g. Drome's unit tests with colors, then everything is almost ok:

![image](https://user-images.githubusercontent.com/2338008/45534059-195c8180-b7fa-11e8-90b5-4e55b2cecbc5.png)

NPM script output for reference:

![image](https://user-images.githubusercontent.com/2338008/45534089-3a24d700-b7fa-11e8-807e-d4d40bd46fad.png)

It seems that Drome omit some colors from output.

**Comment by mikeerickson** [comment]
@kodipe hmmm? I am running on macOS. I debug this when I work on the other two issues.
