### ISSUE TITLE
Add standard CLI commands (--help | -H, --version | -V)

### ISSUE THREAD

**Issue by mikeerickson** [dromejs/drome#15]
## Feature Request

Add some common CLI commands for 

--help | -H
--version | -V

Note: We should likely expand the `drome.config.js` to include the text displayed when issuing `help` command

**Comment by kodipe** [comment]
I'm wondering if help should be a flag `-h`, `--help` or command `drome help`. In the second case we need task name checking for first level tasks.

**Comment by mikeerickson** [comment]
I am following you, I will comment more later today, we are in middle of moving :)

**Comment by kodipe** [comment]
I think that Drome should supports commands (for specific feature) and flags (for modifing behavior).

We should follow up standard like:
```
drome <command> [args] 
```
In that case we should rewrite Drome to support (aliases are nice to have at this moment I think):
- `drome run <task>`
- `drome version` (aliases: `drome -v`, `drome --version` - for now nice to have)
- `drome help` (aliases: `drome -h`, `drome --help`)
- `drome help <task>` (nice to have for now, but in future it would be really cool to have help description also for specific tasks)

if user run just `drome` then it should print help description from `drome help`.
