### ISSUE TITLE
Add global `drome.config.js`

### ISSUE THREAD

**Issue by mikeerickson** [dromejs/drome#16]
## Feature Request

Current functionality requires a `drone.config.js` in each project which may use use tasks.

I think it would be a good idea to create a global config file which could be used across ALL projects.  This config could have some of the common tasks (lint, test, etc) 

Further, we could then allow developers to create their own project specific files and merge then at launch time

Global config
```bash
~/drome.config.js
```

Project config
```bash
~/documents/code/test/drome.config.js
```

Then when drome is launched, we could call `Object.assign` pseudo code (need to do proper file existence check, but you get the picture)

```js
const tasks = Object.assign(path.join(process.cwd(),'/drome.config.js', '~/drome.config.js))
```

**Comment by mikeerickson** [comment]
@kodipe I am ready to move forward on this item if it is OK with you.  I will outline the overall scope before coding anything so that we dont miss any thoughts

**Comment by kodipe** [comment]
@mikeerickson I'm working on something else (and reviewing your PR) right now, so feel free to go on :)

**Comment by mikeerickson** [comment]
Sounds good, will attack in AM after I get real internet speed back
