### ISSUE TITLE
CLI support for commands, flags, variables etc.

### ISSUE THREAD

**Issue by kodipe** [dromejs/drome#17]
## Feature Request

I think that Drome need abstract mechanism to support multiple commands (for specific feature) and flags (for modifing behavior).

We should follow up standard like:
```
drome <command> [args] -- [taskArgs]
```
In that case we should rewrite Drome to support (aliases are nice to have at this moment I think):
- `drome run <task>`
- `drome version` (aliases: `drome -v`, `drome --version`)
- `drome help` (aliases: `drome -h`, `drome --help`)
- `drome help <task>` (nice to have for now, but in future it would be really cool to have help description also for specific tasks)

If user run just `drome` then it should print help description from `drome help`.

Solution should allow easly expand commands/flags list in future

Related issues: #8, #11, #15

**Comment by mikeerickson** [comment]
@kodipe I am working on this task today and am curious if you want to maintain the original `drome.config.js` format, or require users to change their format to use the `extendedTasks` format.

I can convert it at runtime to the "new" format

```js
    {
        name: 'lint',
        command: 'npm run lint',
        alias: 'linty',
        type: 'string',
        description: 'Runs linting process'
    },
```

If I convert at runtime, the the current configuration would become:

```js
const currentConfig = {
    'lint': 'npm run lint',
    'lint:js': 'npm run lint:js',
    'build': 'npm run build'
};

const extendedConfig = [
  { name: 'lint', command: 'npm run lint', alias: 'lint', type: 'string', description: 'npm run lint' },
  { name: 'lint:js', command: 'npm run lint:js', alias: 'lint:js', type: 'string', description: 'npm run lint:js' },
  { name: 'build', command: 'npm run build', alias: 'build', type: 'string', description: 'npm run build' }
]
```

**Comment by mikeerickson** [comment]
@kodipe 

With regards to providing help for a given task, I have been implementing as

```bash
drome <task> -h quick help for <task>
```

This matches the same syntax used by `npm`  

If you want me to change to your proposed syntax, I can do that

```bash
drome help <task>
```

**Comment by kodipe** [comment]
@mikeerickson basicaly, CLI should match `drome <command> <task>` syntax (e.g. `drome run <task>`, `drome help <task>`. I know that syntax similar to this one from `npm` would be great but I think that my proposition allow us to be more flexible in future if Drome will gain some new features.

When it comes to `drome.config.js` format... Current one is quite good for me - user can easily ready which one task is based on command line or which one task is run in sequence or parallel (object notation is already used for parallel tasks - we have to remember about that).
Unfortunately it's not enough because we need also way to put some additional data like description of task etc.. In other side, we need to avoid configuration bloat like in Grunt configuration (which is obviously uncomfortable).

One of solution for that could be helpers for building configuration:

```
const { parallel, task } = require('drome');

module.exports = () => {
  return {
    tasks: {
      test: parallel(
        task("unit", "jest", {description: "Unit test of application"}),
        task("lint", "eslint", {description: "App linting"})
      ),
    }
  }
}
```

It's only initial thought about that - I didn't prepare new configuration schema yet. For now we can convert it in runtime, but after all we need to extend that.

**Comment by kodipe** [comment]
@mikeerickson please have a look at #20 :)
