### ISSUE TITLE
What is your overall thought process to maintaining tasks across mulitple projects

### ISSUE THREAD

**Issue by mikeerickson** [dromejs/drome#9]
## Feature Request

If you have some suggestion in mind please describe:

- **Documentation** - how users will be able to use the new feature

The subject says it all, but in short I am curious as to what your big picture thought process is for managing configuration (tasks) across multiple projects.  I used to be a `gulp` guy, but over the plast couple years, I have moved to using `npm scripts` and/or `bash scripts`

This project is quite intriguing to me and would love to see and watch/assist how it grows.

**Comment by HugoHeneault** [comment]
For anyone joining the discussion there might be an idea here: https://github.com/dromejs/drome/issues/16
